/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_home_jni_msc_MSCGen */

#ifndef _Included_org_home_jni_msc_MSCGen
#define _Included_org_home_jni_msc_MSCGen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_home_jni_msc_MSCGen
 * Method:    generate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_home_jni_msc_MSCGen_generate
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
